name: illumeta
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - r-base=4.4
  - pandoc
  - cmake
  - make
  - pkg-config
  - c-compiler
  - cxx-compiler
  - fortran-compiler
  - libcurl
  - openssl
  - libxml2
  - icu
  - libgit2
  - fontconfig
  - harfbuzz
  - fribidi
  - freetype
  - libpng
  - libtiff
  - libjpeg-turbo
  - libwebp
  - pip:
      - -r requirements.txt
